version: '3.8'

services:

  redis:
    image: redis:7.0.11-alpine

  django:
    container_name: django
    build:
      context: .
      dockerfile: Django_Docker/Dockerfile
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8001:8000
    depends_on:
      - redis
  
  celery:
    container_name: celery
    build:
      context: .
      dockerfile: Celery_Docker/Dockerfile
    # command: celery -A dcelery worker --loglevel=INFO
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - redis
    